FROM fopina/fluent-bit-plugin-dev:v1.7.0-0 as builder

ADD . /myplugin

RUN cmake -DFLB_SOURCE=/usr/src/fluentbit/fluent-bit-1.7.0/ \
          -DPLUGIN_NAME=out_influxdb_v2 ../

RUN make

RUN ls -la

FROM scratch

COPY --from=builder /myplugin/build/flb-out_influxdb_v2.so /
